# Generated by Django 5.2.15 on 2026-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='starting_price_inr',
            field=models.CharField(blank=True, default='₹2,000 - ₹3,500', max_length=50),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='starting_price_usd',
            field=models.CharField(blank=True, default='$25 - $45', max_length=50),
        ),
    ]
