# Generated by Django 5.2.15 on 2026-09-17 06:23

import apps.catalog.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_atelier_license_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/HP/Desktop/Shiuli/shiuli-cad-studio/backend/protected_media')), upload_to=apps.catalog.models.product_file_upload_to),
        ),
    ]
