# Generated by Django 5.2.15 on 2026-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0005_customrequest_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='client_consent_to_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='client_consent_to_feature',
            field=models.BooleanField(default=False),
        ),
    ]
