# Generated by Django 5.2.15 on 2026-09-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0005_customrequest_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='catalog_references_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='custom_specs_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='gold_purity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='download_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
