# Generated by Django 5.2.15 on 2026-09-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0006_customrequest_catalog_references_text_and_more'),
        ('custom_orders', '0006_customrequest_client_consent_to_feature_and_more'),
    ]

    operations = [
    ]
