# Generated by Django 5.2.15 on 2026-09-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0006_customrequest_client_consent_to_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preview_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='custom_orders/previews/'),
        ),
        migrations.AddField(
            model_name='order',
            name='preview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preview_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preview_status',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Booking Payment'), ('in_design', 'In Pool (Awaiting Designer)'), ('with_designer', 'With CAD Designer'), ('preview_pending_approval', 'Preview Sent to Client'), ('preview_approved', 'Preview Approved by Client'), ('revision_requested', 'Preview Revision Requested'), ('pending_review', 'Pending Admin Quality Review'), ('preview_ready', 'Design Preview Ready for Client'), ('pending_final_payment', 'Pending Final Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=35),
        ),
    ]
